# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messanger.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_text = QtWidgets.QTextEdit(self.centralwidget)
        self.login_text.setGeometry(QtCore.QRect(180, 100, 231, 31))
        self.login_text.setObjectName("login_text")
        self.log_label = QtWidgets.QLabel(self.centralwidget)
        self.log_label.setGeometry(QtCore.QRect(30, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.log_label.setFont(font)
        self.log_label.setObjectName("log_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.enter_button = QtWidgets.QPushButton(self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(390, 500, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.enter_button.setFont(font)
        self.enter_button.setIconSize(QtCore.QSize(200, 200))
        self.enter_button.setObjectName("enter_button")
        self.lev_label = QtWidgets.QLabel(self.centralwidget)
        self.lev_label.setGeometry(QtCore.QRect(30, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lev_label.setFont(font)
        self.lev_label.setObjectName("lev_label")
        self.password_text = QtWidgets.QTextEdit(self.centralwidget)
        self.password_text.setGeometry(QtCore.QRect(180, 260, 231, 31))
        self.password_text.setOverwriteMode(True)
        self.password_text.setObjectName("password_text")
        self.pass_label = QtWidgets.QLabel(self.centralwidget)
        self.pass_label.setGeometry(QtCore.QRect(30, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pass_label.setFont(font)
        self.pass_label.setObjectName("pass_label")
        self.password_text_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.password_text_1.setGeometry(QtCore.QRect(180, 320, 231, 31))
        self.password_text_1.setOverwriteMode(False)
        self.password_text_1.setAcceptRichText(False)
        self.password_text_1.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.password_text_1.setObjectName("password_text_1")
        self.pass1_label = QtWidgets.QLabel(self.centralwidget)
        self.pass1_label.setGeometry(QtCore.QRect(30, 290, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pass1_label.setFont(font)
        self.pass1_label.setTextFormat(QtCore.Qt.RichText)
        self.pass1_label.setWordWrap(True)
        self.pass1_label.setObjectName("pass1_label")
        self.checkBox_registr = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_registr.setGeometry(QtCore.QRect(30, 400, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_registr.setFont(font)
        self.checkBox_registr.setObjectName("checkBox_registr")
        self.registr_button = QtWidgets.QPushButton(self.centralwidget)
        self.registr_button.setGeometry(QtCore.QRect(30, 500, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.registr_button.setFont(font)
        self.registr_button.setIconSize(QtCore.QSize(200, 200))
        self.registr_button.setObjectName("registr_button")
        self.level_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.level_combobox.setGeometry(QtCore.QRect(180, 150, 231, 31))
        self.level_combobox.setObjectName("level_combobox")
        self.lev_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.lev_label_2.setGeometry(QtCore.QRect(30, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lev_label_2.setFont(font)
        self.lev_label_2.setObjectName("lev_label_2")
        self.online_RB = QtWidgets.QRadioButton(self.centralwidget)
        self.online_RB.setGeometry(QtCore.QRect(180, 210, 95, 20))
        self.online_RB.setObjectName("online_RB")
        self.offline_RB = QtWidgets.QRadioButton(self.centralwidget)
        self.offline_RB.setGeometry(QtCore.QRect(320, 210, 95, 20))
        self.offline_RB.setObjectName("offline_RB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.log_label.setText(_translate("MainWindow", "Логин:"))
        self.label_2.setText(_translate("MainWindow", "SIMPLE MESSANGER"))
        self.enter_button.setText(_translate("MainWindow", "Вход"))
        self.enter_button.setShortcut(_translate("MainWindow", "Return"))
        self.lev_label.setText(_translate("MainWindow", "Уровень доступа:"))
        self.pass_label.setText(_translate("MainWindow", "Пароль:"))
        self.pass1_label.setText(_translate("MainWindow", "Подтверждение пароля:"))
        self.checkBox_registr.setText(_translate("MainWindow", "Регистрация"))
        self.registr_button.setText(_translate("MainWindow", "Регистрация"))
        self.registr_button.setShortcut(_translate("MainWindow", "Return"))
        self.lev_label_2.setText(_translate("MainWindow", "Статус:"))
        self.online_RB.setText(_translate("MainWindow", "Online"))
        self.offline_RB.setText(_translate("MainWindow", "Offline"))

